Le_Domain='cns.admsiga.org.br'
Le_Alt='no'
Le_Webroot='/usr/share/nginx/html'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='4096'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/2757151641/483603654866'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/2757151641/483603654866'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/054c5a5b23c08b9b5c7ae8214b687361b5fa'
Le_CertCreateTime='1771869617'
Le_CertCreateTimeStr='2026-02-23T18:00:17Z'
Le_RenewalDays='60'
Le_ForceNewDomainKey='1'
Le_NextRenewTimeStr='2026-04-23T18:00:17Z'
Le_NextRenewTime='1776967217'
Le_RealCertPath='/etc/nginx/certs/cns.admsiga.org.br/cert.pem'
Le_RealCACertPath='/etc/nginx/certs/cns.admsiga.org.br/chain.pem'
Le_RealKeyPath='/etc/nginx/certs/cns.admsiga.org.br/key.pem'
Le_ReloadCmd=''
Le_RealFullChainPath='/etc/nginx/certs/cns.admsiga.org.br/fullchain.pem'
